name: linux-build
on: workflow_dispatch
jobs:
  ubuntu_22-04:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - uses: actions/checkout@v3
    - run:
        apt -y update &&
        apt -y install build-essential &&
        cd src &&
        make &&
        mkdir /tmp/bin &&
        cp wg /tmp/bin/wg &&
        cp wg-quick/linux.bash /tmp/bin/wg-quick
    - uses: actions/upload-artifact@v3
      with:
        name: amnezia-wg-tools_ubuntu_22.04
        path: /tmp/bin/
  alpine_3-19:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.19
    steps:
    - uses: actions/checkout@v3
    - run:
        apk add linux-headers build-base &&
        cd src &&
        make &&
        mkdir /tmp/bin &&
        cp wg /tmp/bin/wg &&
        cp wg-quick/linux.bash /tmp/bin/wg-quick
    - uses: actions/upload-artifact@v3
      with:
        name: amnezia-wg-tools_alpine_3.19
        path: /tmp/bin/
